### ISSUE TITLE
configure https connection for neo4j

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1127]

**Comment by originalname51** [comment]
•	openssl pkcs8 -topk8 -inform PEM -outform DER -in gtas-prv.pem -out gtas-prv-pk8.pem –nocrypt is currently incorrect on document and needs to be "-".

**Comment by originalname51** [comment]
Am getting following stack trace:

2019-08-23 18:58:35.330+0000 INFO  ======== Neo4j 3.5.4 ========
2019-08-23 18:58:35.342+0000 INFO  Starting...
2019-08-23 18:58:35.981+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@26d9b808' was successfully initialized, but failed to start. Please see the attached cause exception "signed fields invalid". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@26d9b808' was successfully initialized, but failed to start. Please see the attached cause exception "signed fields invalid".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@26d9b808' was successfully initialized, but failed to start. Please see the attached cause exception "signed fields invalid".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:123)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@26d9b808' was successfully initialized, but failed to start. Please see the attached cause exception "signed fields invalid".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more

**Comment by originalname51** [comment]
Rule engine and ETL job appear to be not working with neo4j. Browser works.

**Comment by TeddyTesfaye** [comment]
The ETL works locally without any issue. 
The HTTPS part should not affect how the ETL works because the ETL does not make HTTP calls

**Comment by kasimhelil** [comment]
checked `https://localhost:7473`, and it worked
