### ISSUE TITLE
Docker: Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 

### ISSUE THREAD

**Issue by johariyan** [US-CBP/GTAS#1779]
**Describe the bug**
Issue installing the app using Docker  :
SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. 
SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/gtas] startup failed due to previous errors

**To Reproduce**
$ git clone --branch dev - 
$ cd GTAS  
$ docker-compose up -d
Application gets installed and up and running , however, following error is shown on the docker log files:
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'EMAIL_SENDER_USERNAME' in value "${EMAIL_SENDER_USERNAME}"

**Expected behavior**
Application suppose to get run and running and accessed browser. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Docker : 2.2.0.5 
 

**Smartphone (please complete the following information):** 
  N/A

**Additional context**
complete log:
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:380)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$26/00000000D1975560.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:853)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4688)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5151)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'EMAIL_SENDER_USERNAME' in value "${EMAIL_SENDER_USERNAME}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211)
	at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:228)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:88)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:62)
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:539)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:137)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:133)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getPropertyAsRawString(PropertySourcesPropertyResolver.java:74)
	at org.springframework.core.env.AbstractPropertyResolver$$Lambda$23/00000000D0AFAA70.resolvePlaceholder(Unknown Source)
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:145)
	at org.springframework.core.env.AbstractPropertyResolver.resolvePlaceholders(AbstractPropertyResolver.java:203)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:174)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$$Lambda$138/00000000D283BFF0.resolveStringValue(Unknown Source)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:851)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	... 65 common frames omitted
19-Apr-2020 19:44:43.573 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
19-Apr-2020 19:44:43.581 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/gtas] startup failed due to previous errors
19-Apr-2020 19:44:43.629 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/gtas.war] has finished in [20,652] ms
19-Apr-2020 19:44:43.633 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-9090"]
19-Apr-2020 19:44:43.641 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-openssl-apr-8443"]
19-Apr-2020 19:44:43.652 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-apr-127.0.0.1-8009"]
19-Apr-2020 19:44:43.658 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [20,758] milliseconds

**Comment by simbamarufu1** [comment]
Thank you for checking out our application. I believe the issue you are experiencing is because of the compose command you are executing to start the application.

Running the following command will start the core application:
docker-compose -f docker-compose.yml -f local-deployment.yml up

Running the following command will start all the system apps including ELK and Neo4j:
docker-compose -f docker-compose.yml -f neo4j-etl-docker-compose.yml -f elk-docker-compose.yml -f local-deployment.yml up

**Comment by johariyan** [comment]
Thanks simbamarufu1 
I managed to install the application without any error, however, still not able to access the web-app, could be due the docker port mapping. I will further investigate the issue and will contact, if need any help. 

Regards,

**Comment by simbamarufu1** [comment]
No worries!

If you have a stack trace or more information to help facilitate troubleshooting, I can also help you address the port mapping issue

**Comment by johariyan** [comment]
Hi Simbamarufu1 , need your advise, I could access the tomcat but webapp is not accessible at all. I used : **docker-compose -f docker-compose.yml -f local-deployment.yml up**
Web App Ports: 
2610/tcp
localhost:2610

8443/tcp
localhost:8443

start-up log attached. 
Do I need to make any manual config changes? 
Thanks for your help in advance. 
[WebApp Log](https://github.com/US-CBP/GTAS/files/4548012/WebApp.Log)

**Comment by simbamarufu1** [comment]
Try https://localhost:8443/gtas

**Comment by johariyan** [comment]
Thanks 
I think, error is due to the ports are already in use.  refer the configtest.sh results for scheduler and webapp.  I managed to change the config using server.xml but webapp is still giving the error. 
[configtest sh result.txt](https://github.com/US-CBP/GTAS/files/4548614/configtest.sh.result.txt)

**Comment by johariyan** [comment]
I managed to get the WebApp up and running and access to access now. currently getting following error on login , which I am working on: 

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: DNS lookup failure for: kibana

**Comment by johariyan** [comment]
Hi simbamarufu1 , could you please help me with this issue, where can I find the logs to check the error in parsing
Admin Screen is showing :
Loading/Parsing errors past 500 messages:
15

**Comment by simbamarufu1** [comment]
The proxy error you are seeing is indicative that kibana was not running concurrent to the proxy. Can you run docker container ls to list the running applications?

**Comment by johariyan** [comment]
All the issues have been resolved and now Kibana and Neo4J are up and running and showing data.  However, there seems to be some problem with logstash 

`[2020-05-08T12:15:07,244][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.2.0"}
[2020-05-08T12:15:08,816][WARN ][logstash.monitoringextension.pipelineregisterhook] xpack.monitoring.enabled has not been defined, but found elasticsearch configuration. Please explicitly set `xpack.monitoring.enabled: true` in logstash.yml
[2020-05-08T12:15:10,791][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://elasticsearch:9200/]}}
[2020-05-08T12:15:11,978][WARN ][logstash.licensechecker.licensereader] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '401' contacting Elasticsearch at URL 'https://elasticsearch:9200/'"}
[2020-05-08T12:15:12,118][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"Got response code '401' contacting Elasticsearch at URL 'https://elasticsearch:9200/_xpack'"}
[2020-05-08T12:15:12,224][ERROR][logstash.monitoring.internalpipelinesource] Failed to fetch X-Pack information from Elasticsearch. This is likely due to failure to reach a live Elasticsearch cluster.
[2020-05-08T12:15:12,776][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/usr/share/logstash/config/logstash-message_delivery_comp.conf"}
[2020-05-08T12:15:12,784][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/usr/share/logstash/config/logstash-message_count_comp.conf"}`

**Comment by simbamarufu1** [comment]
Hi johariyan,

That error is caused by unused features in the ELK stack - they are not concerning. I have a pending task to clean them up

**Comment by johariyan** [comment]
Thanks simbamarufu for all your help. 

A side note: While working on the Admin/ Setting tab, I accidentally left the API version field empty, application allowed to save the details but showing the error on the error logs tab.  I then , recheck the setting tab, and now none of the fields got any value, I entered all the default values and saved again, showed as success but again , nothing got saved in the database. I ended up logging up to the database and restored the values then UI started showing values in the setting tab.  Do you want me to log this an error? I think, application should display some mandatory field validation.
