### ISSUE TITLE
GTAS couldn't parse PNR 11.1

### ISSUE THREAD

**Issue by YumiSuki** [US-CBP/GTAS#2021]
**Describe the bug**
I have tried to feed GTAS with PNR 11.1 but it couldn't parse information. The first time I feed it, it shows that there is no prime flight but the second time, it tells me that it's a duplicate message.  
Here is the logs I first input data:
```
08:43:07.106 [DefaultMessageListenerContainer-1] INFO  g.g.j.s.LoaderQueueThreadManager - New Queue Created For Prime Flight: LAXSYDUA08391292086800000
08:43:07.201 [pool-3-thread-2] ERROR gov.gtas.services.PnrMessageService - ERROR
gov.gtas.services.NoPrimeFlightException: No prime flight. ERROR!!!!!
	at gov.gtas.services.GtasLoaderImpl.processFlightsAndBookingDetails(GtasLoaderImpl.java:600)
	at gov.gtas.services.PnrMessageService.load(PnrMessageService.java:133)
	at gov.gtas.services.PnrMessageService$$FastClassBySpringCGLIB$$54aa9261.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at gov.gtas.services.PnrMessageService$$EnhancerBySpringCGLIB$$fc6310f6.load(<generated>)
	at gov.gtas.services.Loader.processMessage(Loader.java:180)
	at gov.gtas.job.scheduler.LoaderScheduler.processSingleFile(LoaderScheduler.java:119)
	at gov.gtas.job.scheduler.LoaderScheduler.receiveMessage(LoaderScheduler.java:151)
	at gov.gtas.job.scheduler.LoaderWorkerThread.processCommand(LoaderWorkerThread.java:116)
	at gov.gtas.job.scheduler.LoaderWorkerThread.run(LoaderWorkerThread.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
08:43:07.251 [pool-3-thread-2] ERROR gov.gtas.services.PnrMessageService - ERROR
gov.gtas.services.NoPrimeFlightException: No prime flight. ERROR!!!!!
	at gov.gtas.services.GtasLoaderImpl.processFlightsAndBookingDetails(GtasLoaderImpl.java:600)
	at gov.gtas.services.PnrMessageService.load(PnrMessageService.java:133)
	at gov.gtas.services.PnrMessageService$$FastClassBySpringCGLIB$$54aa9261.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at gov.gtas.services.PnrMessageService$$EnhancerBySpringCGLIB$$fc6310f6.load(<generated>)
	at gov.gtas.services.Loader.processMessage(Loader.java:180)
	at gov.gtas.job.scheduler.LoaderScheduler.processSingleFile(LoaderScheduler.java:119)
	at gov.gtas.job.scheduler.LoaderScheduler.receiveMessage(LoaderScheduler.java:151)
	at gov.gtas.job.scheduler.LoaderWorkerThread.processCommand(LoaderWorkerThread.java:116)
	at gov.gtas.job.scheduler.LoaderWorkerThread.run(LoaderWorkerThread.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

And then the second and third time I input data, I got:
```
09:05:07.155 [DefaultMessageListenerContainer-2] INFO  g.g.j.s.LoaderQueueThreadManager - New Queue Created For Prime Flight: LAXSYDUA08391292086800000
09:05:07.166 [pool-3-thread-5] INFO  gov.gtas.services.GtasLoaderImpl - Duplicate message, message ignored. hashcode is: 9A10A8FD23C59B51A3B7FFDA0C3B8DBD
09:05:07.180 [pool-3-thread-5] INFO  gov.gtas.services.GtasLoaderImpl - Duplicate message, message ignored. hashcode is: 3ED7688CF4957D8AABFB83757B6DA0CA
09:05:08.190 [pool-3-thread-5] INFO  g.g.job.scheduler.LoaderWorkerThread - Self-Destruct: Queue Removed, Thread Destroyed
```

Here is some data I found on the internet and feed to GTAS:
- https://na.eventscloud.com/file_uploads/86d49ce95953d6a3d1e0b18d3c8baf17_D2TT2michqelodgers-PeterBrennan.pdf
```
UNA:+.?*'UNB+IATA:1+UA+AUCBPS+101209:2100+020A07'UNH+1+PNRGOV:11:1:IA+F6C2C268+12'MSG+:22'ORG+DL:ATL+52519950'TVL+121210:0915+LAX+SYD+UA+839'EQN+2'SRC'RCI+DL:MFN4TI'SSR+AVML:HK:2:DL'DAT+700:061210:1010+710:061210:1200'IFT+4:28::DL+THIS PASSENGER IS A VIP'IFT+4:28::DL+CTCR 00115555555555'ORG+DL:ATL+52519950:LON+++A+GB:GBP+D050517'ADD++702:45 HIGH STREET:SLOUGH:BERKSHIRE::GB:SL1AA:00441753637285'EBD+GBP:40.00+4::N'TIF+SMITHJR+JOHNMR:A:1'FTI+DL:1234567890:::ELITE'FT+4:15:9+LHR DL X/JFK DL YVR GBP/IT  END ROE0.618831XT3.10AY6IFT+8.50YQ3.40+YC4.30XY3.10XA2.80XFATL4.5'REF+:38739393AN8739P'FAR+N+++++MIL24'SSR+DOCS:HK::DL:::::/P/GBR/123456789/GBR/12JUL64/M/23AUG19/SMITHJR/JONATHON/ROBERT'TKT+0062120234533:T:1'MON+B:2888.00:GBP+T:2957.94:GBP'PTK+NR++061210:1010+DL+006+LON'TXD++3.10:::AY+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'DAT+710:061210:1200'FOP+CC:::VI:XXXXXXXX1186:0211'IFT+4:43+TIMOTHY SIMS+2234MAIN STREET ATLANTA, GA 30067+770 5632891'TIF+JONES+WILLIAMMR:A:2'FTI+AF:0093789865:::ELITE'IFT+4:15:9+ LHR DL X/JFK DL YVR GBP/IT  END ROE0.618831 XT3.10AY68.50YQ3.40+YC4.30XY3.10XA2.80XFATL4.5'REF+:38739393AN8780P'FAR+A+++++YN324N'SSR+DOCS:HK::DL:::::////GBR/12JUL64/M//JONES/WILLIAMNEVELL'TKT+0062120234534:T:1'MON+B:2888.00:GBP+T:2957.94:GBP'PTK+NR++061210:1010+DL+006+LON'TXD++3.10:::AY+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'DAT+710:081210:1200'FOP+CC:::VI:XXXXXXXX1186:0211'IFT+4:43+TIMOTHY SIMS+2234 MAIN STREET ATLANTA, GA 30067+770 5632891'TVL+121210:0915::1230+LHR+JFK+DL+324:B'RPI+2+HK'APD+767'SSR+SEAT:HK:2:DL:::LHR:JFK+15A::1+15B::2'DAT+2:111210:0915'TRI++108:::1'TIF+SMITHJR+JOHNMR:A:1'SSD+15A++++Y'TVL+121210:2200::2330+JFK+YVR+DL+330:B'RPI+2+HK'APD+767'SSR+SEAT:HK:2:DL:::JFK:YVR+15E::1+15F::2'EQN+1'RCI+DL:ABCDEF'MSG+8'TVL+121210:1500:151210+YVR:VANCOUVER ARMS++VN+67576:ROH'ABI+1+:LHRRR+LON++DL'DAT+ZT:071210:1010'SAC+++X'TVL+101210:0915::1230+LHR+JFK+DL+324:B'RPI+2+K'SAC+++X'SSR+AVML:HK:2:DL'SAC+++X'SSR+SEAT:HK:2:DL:::LHR:JFK+15A::1+15B::2'SAC+++X'TVL+101210:2200::2330+JFK+YVR+DL+330:B'RPI+2+K'SAC+++X'SSR+AVML:HK:2:DL'SAC+++X'SSR+SEAT:HK:2:DL:::JFK:YVR+15E::1+15F::2'SAC+++X'TVL+121210:0915::1230+LHR+JFK+DL+324:B'RPI+2+K'SAC+++X'SSR+AVML:HK:2:DL'SAC+++X'SSR+SEAT:HK:2:DL:::LHR:JFK+15A::1+15B::2'SAC+++X'TVL+121210:2200::2330+JFK+YVR+DL+330:B'RPI+2+K'SAC+++X'SSR+AVML:HK:2:DL'SAC+++X'SSR+SEAT:HK:2:DL:::JFK:YVR+15E::1+15F::2'SRC'RCI+1A:23456'DAT+700:061210:1010+710:061210:1200'ORG+1A:MUC+12345678:F31+LON++T+GB:GBP+A78987'ADD++702:351 LANDSDOWNROAD:SLOUGH:BERKSHIRE::GB::SL1AA'EBD+GBP:20.00+2::N'TIF+WAYNE+JOHNMR:A:1'FTI+DL:1234567893:::ELITE'IFT+4:15:9+LHR DL X/JFK DLYVR GBP/IT  END ROE0.618831XT3.10AY6 8.50+YQ3.40YC4.30XY3.10XA2.80XFATL4.5'REF+:38739393AN8740P'FAR+A+++++YN324N'SSR+DOCS:HK::DL:::::/P/GBR/123456789/GBR/12JUL12/M/23AUG15/WAYNE/JOHNALVA'TKT+0062120234535:T:1'MON+B:2888.00:GBP+T:2957.94:GBP'PTK+NR++061210:1010+DL+006+LON'TXD++3.10:::AY+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'DAT+710:061210:1200'FOP+CC:::VI:XXXXXXXX1186:0211'TIF+COOPER+GARYMR:A:2'FTI+AF:0093789830:::ELITE'IFT+4:15:9+ LHR DL X/JFK DL YVR GBP/IT  END ROE0.618831 XT3.10AY6 8.50+YQ3.40YC4.30XY3.10XA2.80XFATL4.5'REF+:38739393AN8793P'FAR+A+++++YN324N'SSR+DOCS:HK::DL:::::/P/GBR/987654321/GBR/12JUL15/M/15JAN13/COOPER/GARYWILLIAM'TKT+0062120234536:T:1'MON+B:2888.00:GBP+T:2957.94:GBP'PTK+NR++061210:1010+DL+006+LON'TXD++3.10:::AY+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'DAT+710:061210:1200'FOP+CC:::DC:XXXXXXXX3578:0211'TVL+121210:0915::1230+LHR+JFK+DL+324:B'RPI+1+HK'APD+767'SSR+SEAT:HK:2:DL:::LHR:JFK++17A::1+17B::2'DAT+2:111210:0915'TRI++2:::1'TIF+COOPER+GARYMR:A:2'SSD+15A++++Y'TVL+121210:2200::2330+JFK+YVR+DL+330:B'RPI+1+HK'APD+767'SSR+SEAT:HK:2:DL:::JFK:YVR+17E::1+17F::2'ABI+1+:LHRRR+LON++DL'DAT+701:071210:1010'SAC+++X'TIF+WAYNE+JONMR:A:1'SAC+++X'TIF+WAYNE+JOHNMR:A:1'UNT+135+1'UNZ+1+020A07'
```

- https://github.com/EdiFabric/EDIFACT.NET/blob/master/Files/EDIFACT/PassengerData.txt
```
UNA:+.?*'
UNB+IATA:1+AM+MXPNRGOV+130522:1540+13052210400995+PNRGOV'
UNG+PNRGOV+AM+MXPNRGOV+130522:1540+13052210400995+IA+11:1'
UNH+13052210400995+PNRGOV:11:1:IA+AM498/230513/1142'
MSG+:22'
ORG+AM'
TVL+230513:1039:230513:1142+MTY+LAS+AM+498'
EQN+1'
SRC'
RCI+AM:XXXYET::300413:115500'
SSR+OTHS:::::::: ADV TKT NUMBER BY 03MAY13 1800CO OR WILL CANCEL'
SSR+OTHS:::::::: IF THE FARE RULE TL DIFFERS FROM THE AUTOMATIC'
SSR+OTHS:::::::: TL THE MOST RESTRICTIVE TL WILL APPLY'
DAT+700:180513:1502'
ORG+AM:BOG'
TIF+TESTSURNAMEONE+TESTNAMEONE MRS:A:1.1:1'
SSR+INFT:NN:1:AM:::::TESTSURNAMETWO/TESTNAMETWO/10AUG11+::1.1'
SSR+INFT:NN:1:AM:::::TESTSURNAMETWO/TESTNAMETWO/10AUG11+::1.1'
SSR+TKNE:HK:1:AM:::MEX:CUN:1392178947000C2+::1.1'
SSR+TKNE:HK:1:AM:::CUN:BOG:1392178947000C3+::1.1'
SSR+TKNE:HK:1:AM:::MEX:CUN:INF1392178947000C2+::1.1'
SSR+TKNE:HK:1:AM:::CUN:BOG:INF1392178947000C3+::1.1'
SSR+DOCS:HK:1:AM:::::/P/CO/52263000/CO/30MAY76/F/31OCT15/TESTSURNAMEONE/TESTNAMEONE MRS+::1.1'
SSR+DOCS:HK:1:AM:::::/P/COL/AO234000/COL/10AUG11/FI/21DEC22/TESTSURNAMETWO/TESTNAMETWO+::1.1'
TIF+TESTSURNAMETWO+TESTNAMETWO:IN:2.1'
IFT+4:28+AM INF'
TVL+150513:0105:150513:0557+BOG+MEX+AM+709:R'
RPI+1+YG'
APD+737'
RCI+AM:XXXYET::300413:115500'
TVL+190513:1500:190513:1710+MEX+CUN+AM+445:S'
RPI+1+HK'
APD+738'
SSR+INFT:NN:1:AM:::::TESTSURNAMETWO/TESTNAMETWO/10AUG11'
SSR+TKNE:HK:1:AM:::MEX:CUN:1392178947000C2'
SSR+TKNE:HK:1:AM:::MEX:CUN:INF1392178947000C2'
RCI+AM:XXXYET::300413:115500'
TVL+230513:0135:230513:0500+CUN+BOG+AM+718:Q'
RPI+1+HK'
APD+737'
SSR+INFT:NN:1:AM:::::TESTSURNAMETWO/TESTNAMETWO/10AUG11'
SSR+TKNE:HK:1:AM:::CUN:BOG:1392178947000C3'
SSR+TKNE:HK:1:AM:::CUN:BOG:INF1392178947000C3'
RCI+AM:XXXYET::300413:115500'
UNT+42+13052210400995'
UNE+1+13052210400995'
UNZ+1+13052210400995'
```

**Comment by dje04001** [comment]
Hi @YumiSuki,

You're receiving this error because the TVL0 in both messages (TVL+121210:0915+LAX+SYD+UA+839' and TVL+230513:1039:230513:1142+MTY+LAS+AM+498' respectively) do not appear to match any of the TVL5 values in their respective messages.

The TVL0 must have a corresponding TVL5 for GTAS to consider the message valid. Requirements for a complete TVL0 and TVL5 can differ in different specifications, but the required elements must match.

Simply put, this is bad test data and a production system should treat it as such. A passengers reservation details (TVL5) should contain a flight segment that corresponds for the reason a border security agency has the right to collect and store this information (TVL0).

If you copy TVL+230513:0135:230513:0500+CUN+BOG+AM+718:Q' and paste it over TVL+230513:1039:230513:1142+MTY+LAS+AM+498' in the second message, it should load for you.

I hope this helps--

**Comment by YumiSuki** [comment]
Hi @dje04001,
I do appreciate your help and it does work. But I have another PNR that GTAS only parse flight information but doesn't parse passenger information. I saw nothing on the console so I couldn't figure out what is going on.
Here is the PNR:
```
UNA:+.?*'
UNB+IATA:1+K1+CNPNR+210215:0135+21021419350813+PNRGOV'
UNG+PNRGOV+K1+CNPNR+210215:0135+21021419350813+IA+11:1'
UNH+21021419350813+PNRGOV:11:1:IA+K1168/160221/1215'
MSG+:22'
ORG+K1'
TVL+160221:0835:160221:1215+VIE+CAN+K1+168'
EQN+4'

SRC'
RCI+K1:EIZVDS:1:120121:074800'
DAT+700:120121:0749'
ORG+K1:JYY'
ADD++4:::::::JYY1--23234692352-H-1.1+4:::::::JYY---H-1.1'
TIF+TESTUSER+USERTEST:A:1'
IFT+4:61+TESTUSER.USERTEST@EXAMPLE.COM'
REF+:K1AEIZVDS001'
FAR++++++AOWB'
SSR+TKNE:HK:1:K1:::VIE:CAN:1882103670035C1+::1'
TKT+1882103670035:702'
MON+B:421.00:USD+T:506.00:USD'
PTK+N+++K1:K1+188+:KH'
TXD++45.00::USD:YQF+10.00::USD:YRI+25.00::USD:KX+5.00::USD:L5'
DAT+710:120121:2048'
FOP+CC::506.00:VI:XXXXXXXXXXXX0020:0300'
TVL+160221:0835:160221:1215+VIE+CAN+K1+168:A'
RPI+1+HK'
APD+320'
SSR+BRND:NN:1:K1:::VIE:CAN:LB'
SSR+TKNE:HK:1:K1:::VIE:CAN:1882103670035C1+::1'
RCI+K1:EIZVDS:1:120121:074800'
UNT+117+21021419350813'
UNE+1+21021419350813'
UNZ+1+21021419350813'
```

By the way, there is another question, how can I know which field is require by GTAS? Thanks.
