### ISSUE TITLE
What is the maximum allowed size for a message?

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#242]
I'm receiving an error for a PNR that's 70kb. That's a full flight of passengers booking a round trip. Although unlikely, the system should be prepared to handle large messages. What is the current file size  limitation?

**Comment by svempati2006** [comment]
We can store upto 4GB raw file in message table.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by tjwdev** [comment]
gov.gtas.services.LoaderException: exceeds max file size
	at gov.gtas.services.Loader.processMessage(Loader.java:53)
	at gov.gtas.job.scheduler.LoaderScheduler.processSingleFile(LoaderScheduler.java:152)
	at gov.gtas.job.scheduler.LoaderScheduler.processInputAndOutputDirectories(LoaderScheduler.java:137)
	at gov.gtas.job.scheduler.LoaderScheduler.jobScheduling(LoaderScheduler.java:116)
	at sun.reflect.GeneratedMethodAccessor334.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by svempati2006** [comment]
The loader is limiting file size to 64000 bytes.Changed it to accommodate
4294967295 bytes (4GB).Any message with size 4GB can now be accepted by the
Loader.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by dje04001** [comment]
test passed.
