### ISSUE TITLE
Parsing and loading message files -- invalid passenger

### ISSUE THREAD

**Issue by jtangGitHub** [US-CBP/GTAS#305]
16:43:23.397 [pool-2-thread-2] ERROR gov.gtas.services.PnrMessageService - gov.gtas.parsers.exception.ParseException: Invalid passen
at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup2_Passenger(PnrGovParser.java:234)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup1_PnrStart(PnrGovParser.java:158)
	at gov.gtas.parsers.pnrgov.PnrGovParser.parsePayload(PnrGovParser.java:92)
	at gov.gtas.parsers.edifact.EdifactParser.parse(EdifactParser.java:83)
	at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:64)
	at gov.gtas.services.Loader.processMessage(Loader.java:93)

**Comment by svempati2006** [comment]
More stack trace with null passenger values..
13:37:50.794 [main] ERROR gov.gtas.services.PnrMessageService - gov.gtas.parsers
.exception.ParseException: Invalid passenger: gov.gtas.parsers.vo.PassengerVo@33
50162f[
  travelerReferenceNumber=9993274969
  title=MRS
  firstName=<null>
  middleName=<null>
  lastName=<null>
  suffix=<null>
  gender=<null>
  citizenshipCountry=GBR
  residencyCountry=<null>
  passengerType=P
  age=0
  dob=<null>
  embarkation=<null>
  debarkation=<null>
  deleted=false
  documents=[gov.gtas.parsers.vo.DocumentVo@7bc01398[
  documentType=P
  documentNumber=516442192
  expirationDate=<null>
  issuanceDate=<null>
  issuanceCountry=GBR
]]
  seatAssignments=[]
]
        at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup2_Passenger(PnrGovPa
rser.java:234)
        at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup1_PnrStart(PnrGovPar
ser.java:158)
        at gov.gtas.parsers.pnrgov.PnrGovParser.parsePayload(PnrGovParser.java:9
2)
        at gov.gtas.parsers.edifact.EdifactParser.parse(EdifactParser.java:83)
        at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:64)
        at gov.gtas.services.Loader.processMessage(Loader.java:93)
        at gov.gtas.services.LoaderMain.processSingleFile(LoaderMain.java:162)
        at gov.gtas.services.LoaderMain.processInputAndOutputDirectories(LoaderM
ain.java:103)
        at gov.gtas.services.LoaderMain.main(LoaderMain.java:73)

Apr 13, 2017 1:37:50 PM com.hazelcast.partition.InternalPartitionService
