### ISSUE TITLE
Parsing and loading message files - NullPointerException

### ISSUE THREAD

**Issue by jtangGitHub** [US-CBP/GTAS#306]
18:07:26.087 [pool-2-thread-2] ERROR gov.gtas.services.PnrMessageService - java.lang.NullPointerException
    at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup2_Passenger(PnrGovParser.java:216)
    at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup1_PnrStart(PnrGovParser.java:158)
    at gov.gtas.parsers.pnrgov.PnrGovParser.parsePayload(PnrGovParser.java:92)

**Comment by jtangGitHub** [comment]
Add code to check if address information is null.
