### ISSUE TITLE
Parsing and Loading message files - java.lang.NullPointerException

### ISSUE THREAD

**Issue by jtangGitHub** [US-CBP/GTAS#307]
18:07:39.788 [pool-2-thread-2] ERROR gov.gtas.services.PnrMessageService - java.lang.NullPointerException
    at gov.gtas.model.DwellTime.<init>(DwellTime.java:33)
    at gov.gtas.services.PnrMessageService.setDwelTime(PnrMessageService.java:205)
    at gov.gtas.services.PnrMessageService.calculateDwellTimes(PnrMessageService.java:190)
    at gov.gtas.services.PnrMessageService.load(PnrMessageService.java:104)
    at gov.gtas.services.Loader.processMessage(Loader.java:94)
    at gov.gtas.job.scheduler.LoaderScheduler.processSingleFile(LoaderScheduler.java:165)
    at

**Comment by svempati2006** [comment]
Code fixes were checked in.
