### ISSUE TITLE
Parsing and Loading message files - java.lang.NullPointerException

### ISSUE THREAD

**Issue by jtangGitHub** [US-CBP/GTAS#308]
18:08:37.736 [pool-2-thread-2] ERROR gov.gtas.services.PnrMessageService - java.lang.NullPointerException
    at gov.gtas.parsers.util.FlightUtils.padFlightNumberWithZeroes(FlightUtils.java:65)
    at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup5_Flight(PnrGovParser.java:350)
    at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup1_PnrStart(PnrGovParser.java:166)
    at gov.gtas.parsers.pnrgov.PnrGovParser.parsePayload(PnrGovParser.java:92)
    at gov.gtas.parsers.edifact.EdifactParser.parse(EdifactParser.java:83)
    at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:64)
    at gov.gtas.services.Loader.processMessage(Loader.java:93)

**Comment by jtangGitHub** [comment]
No flight number is provided and the message is rejected and logged correctly.
