### ISSUE TITLE
Request for GTAS-PNR and API data files

### ISSUE THREAD

**Issue by RamakriJaya** [US-CBP/GTAS#51]
We have pulled the source from the GitHub repository , and have done a build and deploy of the application on the Tomcat server.
Also followed the install.md file for the initial setup on the MariaDB.
We are able to launch the application from using the localhost url , and able to navigate across pages.
Username :admin
Password:   password

But using the above we are unable to get any records in the different pages.

In the UPLOAD page we are not sure where to pick the PNR and API files to upload flight data.
Could you please help on exactly where to look for the PNR and API data files?

**Comment by copenhafer** [comment]
Thank you for your interest.

I uploaded some additional test files.  Please see gtas-parent/gtas-loader/src/test/resources under the apis-messages and pnr-messages directories.  For APIS, there's also a python script apisgen.py for generating sample files.

To load files, the easiest approach is probably just to run the loader from the command line as follows:

java -jar ./gtas-loader/target/gtas-loader.jar [PNR files]

You can also configure the GTAS scheduler war to work with the upload feature on the UI.  Refer to instructions in install.md.

Note that the sample data is all historical, so you'll have to adjust the departure date on the UI to view the flights.

Let us know if you have any further issues.

**Comment by RamakriJaya** [comment]
Hi
We have followed the install.md to run the gtas-loader.jar
But unfortunately, unable to export the data. 
Also when we run the application, we get an exception in the console on the RuleRunnerScheduler.java line number 66 .NPE.
java.lang.NullPointerException: null
	at gov.gtas.job.scheduler.RuleRunnerScheduler.jobScheduling(RuleRunnerScheduler.java:66) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[gtas-loader-0.1-SNAPSHOT.jar:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[gtas-loader-0.1-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]

Could you again detail what needs to be done to run the loader so data is exported correctly.
Also please let us know how are the values for the hits_summary , passengers,hits_counts populated?
Are they populated by exporting the gtas-loader.jar?

Thank you
Jayabalambika.R

**Comment by copenhafer** [comment]
It's not clear to me how you're running the loader.  

The stacktrace you provided is from the Rule Runner, not the loader.  Did you grab it from the tomcat logs?  It's likely from the gtas-job-scheduler.war which you deployed separately.  I checked in a small fix to at least avoid the NPE.

Did you run the loader from the command line like I suggested?

java -jar ./gtas-loader/target/gtas-loader.jar [PNR or APIS files]

You provide the APIS or PNR files on the command line.  Please do this and provide the FULL output from running the command if you're still having problems.

Also, please send me an email: mikecope (at) gmail.com
