### ISSUE TITLE
Null Pointer Exceptions

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#585]
the prod data has some null pointers that need to be checked out.

**Comment by dje04001** [comment]
gov.gtas.parsers.exception.ParseException: java.lang.NumberFormatException: For input string: "10D1D500089C3B34"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at gov.gtas.parsers.pnrgov.PnrUtils.getBagTagFromElement(PnrUtils.java:381)
	at gov.gtas.parsers.pnrgov.segment.TBD.<init>(TBD.java:144)
	at sun.reflect.GeneratedConstructorAccessor113.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gov.gtas.parsers.edifact.SegmentFactory.build(SegmentFactory.java:21)
	at gov.gtas.parsers.edifact.EdifactParser.getNextSegment(EdifactParser.java:165)
	at gov.gtas.parsers.edifact.EdifactParser.getConditionalSegment(EdifactParser.java:147)
	at gov.gtas.parsers.edifact.EdifactParser.getConditionalSegment(EdifactParser.java:143)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup7_SeatInfo(PnrGovParser.java:553)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup6_Agent(PnrGovParser.java:504)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processFlightSegments(PnrGovParser.java:460)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup5_Flight(PnrGovParser.java:375)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup1_PnrStart(PnrGovParser.java:171)
	at gov.gtas.parsers.pnrgov.PnrGovParser.parsePayload(PnrGovParser.java:95)
	at gov.gtas.parsers.edifact.EdifactParser.parse(EdifactParser.java:83)
	at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:68)
	at gov.gtas.services.Loader.processMessage(Loader.java:93)
	at gov.gtas.services.LoaderMain.processSingleFile(LoaderMain.java:162)
	at gov.gtas.services.LoaderMain.processListOfFiles(LoaderMain.java:90)
	at gov.gtas.services.LoaderMain.main(LoaderMain.java:70)

	at gov.gtas.parsers.edifact.SegmentFactory.build(SegmentFactory.java:25)
	at gov.gtas.parsers.edifact.EdifactParser.getNextSegment(EdifactParser.java:165)
	at gov.gtas.parsers.edifact.EdifactParser.getConditionalSegment(EdifactParser.java:147)
	at gov.gtas.parsers.edifact.EdifactParser.getConditionalSegment(EdifactParser.java:143)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup7_SeatInfo(PnrGovParser.java:553)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup6_Agent(PnrGovParser.java:504)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processFlightSegments(PnrGovParser.java:460)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup5_Flight(PnrGovParser.java:375)
	at gov.gtas.parsers.pnrgov.PnrGovParser.processGroup1_PnrStart(PnrGovParser.java:171)
	at gov.gtas.parsers.pnrgov.PnrGovParser.parsePayload(PnrGovParser.java:95)
	at gov.gtas.parsers.edifact.EdifactParser.parse(EdifactParser.java:83)
	at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:68)
	at gov.gtas.services.Loader.processMessage(Loader.java:93)
	at gov.gtas.services.LoaderMain.processSingleFile(LoaderMain.java:162)
	at gov.gtas.services.LoaderMain.processListOfFiles(LoaderMain.java:90)
	at gov.gtas.services.LoaderMain.main(LoaderMain.java:70)

**Comment by svempati2006** [comment]
This is duplicate ticket and already taken care with another ticket(Ticket 628 Exception 4).
