### ISSUE TITLE
NPE | elastic search helper

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#689]
java.lang.NullPointerException
	at gov.gtas.services.search.ElasticHelper.indexFlightPax(ElasticHelper.java:325)
	at gov.gtas.services.search.ElasticHelper.indexPnr(ElasticHelper.java:156)
	at gov.gtas.services.PnrMessageService.createMessage(PnrMessageService.java:306)
	at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:85)
	at gov.gtas.services.Loader.processMessage(Loader.java:93)
	at gov.gtas.job.scheduler.LoaderScheduler.processSingleFile(LoaderScheduler.java:185)
	at gov.gtas.job.scheduler.LoaderScheduler.lambda$processInputAndOutputDirectories$1(LoaderScheduler.java:170)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at gov.gtas.job.scheduler.LoaderScheduler.processInputAndOutputDirectories(LoaderScheduler.java:168)
	at gov.gtas.job.scheduler.LoaderScheduler.jobScheduling(LoaderScheduler.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

THIS IS ALL SYNTHETIC DATA

UNB+IATA:1+EI++171011:1013+020A07'
UNH+1+PNRGOV:10:1:IA+F6C2C268'
MSG+:22'
ORG+EI:IAD+30096'
TVL+100717:1230+DUB+IAD+EI+119'
EQN+1'
SRC'
RCI+EI:E422A0:310517:1145'
DAT+700:070717:1230+710:310517:1145'
ORG+DL:IAD+70379193:LON+++A+GB:GBP+D050517'
ADD++702:9869 NORGATE AVENUE:CHENNAI:::IN::800850997818'
TIF+FORSYTH+MORGANMR:A:1'
FTI+EI:399375:::ELITE'
IFT+4:28::YY+CTCE MORGAN..FORSYTH//GMAIL.COM'
REF+:216151692'
FAR+N+++++MIL24'
SSR+DOCS:HK::DL:::::/P/GBR/158278547//11APR81/M/11NOV20/FORSYTH/MORGANMR/LUCAS'
TKT+41374041374041:T:1'
MON+B:2888.00:GBP+T:2957.94:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++3.10:::AY6+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'
DAT+710:130417:0000'
FOP+CA::300.00'
TIF+FORSYTH+AVAMRS:A:2'
FTI+EI:34650:::ELITE'
IFT+4:28::YY+CTCE AVA.FORSYTH//YAHOO.COM'
REF+:916040702'
FAR+N+++++MIL24'
SSR+DOCS:HK::DL:::::/P/GBR/402247336//20DEC90/F/10MAY26/FORSYTH/AVAMRS/ABIGAIL'
TKT+17041017041017:T:1'
MON+B:2888.00:GBP+T:2957.94:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++3.10:::AY6+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'
DAT+710:130417:0000'
CC+::300.00:VI:XXXXXXXXXXXX3535:0917'
TVL+100717:1230::1535+DUB+IAD+EI+119:B'
APD+777'
SSR+SEAT:HK:2:EI:::DUB:IAD+1K::1+19D::2'
RCI+EI:E422A0'
DAT+2:100717:1030'
TRI++1:::1'
TIF+FORSYTH+MORGANMR:A:1'
SSD+1K++++Y'
TBD++01:59:701+++EI:::DUB:006'TRI++2:::2'
TIF+FORSYTH+AVAMRS:A:2'
SSD+19D++++Y'
TBD++01:24:701+++EI:0001::DUB:006'
TVL+150717:1715:160717:0520+IAD+DUB+EI+118:B'
APD+'
SSR+SEAT:HK:2:EI:::IAD:DUB++1K::1+19D::2'
RCI+EI:E422A0'
DAT+2:150717:1515'
TRI++1:::1'
TIF+FORSYTH+MORGANMR:A:1'
SSD+1K++++Y'
TBD++01:59:701+++EI:::DUB:006'TRI++2:::2'
TIF+FORSYTH+AVAMRS:A:2'
SSD+19D++++Y'
TBD++01:24:701+++EI:0001::DUB:006'
ABI+1+:LHRRR+LON++DL'
DAT+ZT:071210:1010'
UNT+63'
UNZ+1+020A07'

**Comment by donleyac** [comment]
Is that the entire pnr, it's honestly a weird issue so I'd like to load the message and run through the program with it?

**Comment by dje04001** [comment]
I attached one pnr message to the ticket that results in a npe. That should
be the entire pnr.

**Comment by donleyac** [comment]
I seem to be getting a PNR Parsing Error for this message, that could be a reason why it is throwing errors when putting it into Elastic. 

 ERROR gov.gtas.services.PnrMessageService - gov.gtas.parsers.exception.ParseException: Expected segment UNT but got CC
	at gov.gtas.parsers.edifact.EdifactParser.getNextSegment(EdifactParser.java:169)
	at gov.gtas.parsers.edifact.EdifactParser.getMandatorySegment(EdifactParser.java:135)
	at gov.gtas.parsers.edifact.EdifactParser.getMandatorySegment(EdifactParser.java:126)
	at gov.gtas.parsers.edifact.EdifactParser.parseTrailer(EdifactParser.java:103)
	at gov.gtas.parsers.edifact.EdifactParser.parse(EdifactParser.java:84)
	at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:68)
	at gov.gtas.services.Loader.processMessage(Loader.java:93)
	at gov.gtas.job.scheduler.LoaderScheduler.processSingleFile(LoaderScheduler.java:185)
	at gov.gtas.job.scheduler.LoaderScheduler.lambda$processInputAndOutputDirectories$1(LoaderScheduler.java:170)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at gov.gtas.job.scheduler.LoaderScheduler.processInputAndOutputDirectories(LoaderScheduler.java:168)
	at gov.gtas.job.scheduler.LoaderScheduler.jobScheduling(LoaderScheduler.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by dje04001** [comment]
There's a .pdf in the Google drive for UN EDIFACT standard. In the first
few pages, there's a tree diagram that lays out the message grammar. Can
you see if the message fits this  grammar, or if i made bad data?

**Comment by donleyac** [comment]
For that segment Edifact requires a FOP segment, which can be followed by an IFT and ADD
![uploads/73198f37-dce0-43bd-94d6-bf53a6c0081d/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F73198f37-dce0-43bd-94d6-bf53a6c0081d%2Fimage.png)

There are some instances in which DAT proceeds a UNT segment but it doesn't appear that this is the case. A RCI or TVL would usually be before the DAT for that scenario. 
![uploads/7d6d8a1a-4f8d-4964-a074-5e7b98d58ec1/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7d6d8a1a-4f8d-4964-a074-5e7b98d58ec1%2Fimage.png)

**Comment by svempati2006** [comment]
I am able to reproduce both the exceptions in my local.Even the loader throws a parsing exception the elastic helper is trying to index the empty passengers and flight information where we are getting a NPE.
Will fix the code only to index when we have valid PNR,APIS with flights and passengers..from my local..
stack trace is 
java.lang.NullPointerException
	at gov.gtas.services.search.ElasticHelper.indexFlightPax(ElasticHelper.java:329)
	at gov.gtas.services.search.ElasticHelper.indexPnr(ElasticHelper.java:158)
	at gov.gtas.services.PnrMessageService.createMessage(PnrMessageService.java:306)
	at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:85)
	at gov.gtas.services.Loader.processMessage(Loader.java:93)
	at gov.gtas.services.LoaderMain.processSingleFile(LoaderMain.java:162)
	at gov.gtas.services.LoaderMain.processInputAndOutputDirectories(LoaderMain.java:103)
	at gov.gtas.services.LoaderMain.main(LoaderMain.java:73)

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GitHub Dev branch.Pl review.
After code fix the parsing exception is getting stored instead of ElasticHelpers NPE..
Message table now has the actual parsing Exception:
gov.gtas.parsers.exception.ParseException: Expected segment UNT but got CC
	at gov.gtas.parsers.edifact.EdifactParser.getNextSegment(EdifactParser.java:169)
	at gov.gtas.parsers.edifact.EdifactParser.getMandatorySegment(EdifactParser.java:135)
	at gov.gtas.parsers.edifact.EdifactParser.getMandatorySegment(EdifactParser.java:126)
	at gov.gtas.parsers.edifact.EdifactParser.parseTrailer(EdifactParser.java:103)
	at gov.gtas.parsers.edifact.EdifactParser.parse(EdifactParser.java:84)
	at gov.gtas.services.PnrMessageService.parse(PnrMessageService.java:68)
	at gov.gtas.services.Loader.processMessage(Loader.java:93)
	at gov.gtas.services.LoaderMain.processSingleFile(LoaderMain.java:162)
	at gov.gtas.services.LoaderMain.processInputAndOutputDirectories(LoaderMain.java:103)
	at gov.gtas.services.LoaderMain.main(LoaderMain.java:73)
