### ISSUE TITLE
Enhanced Manifest exception

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#721]
enhanced manifest message fails to load.

gov.gtas.services.LoaderException: unrecognized file type
	at gov.gtas.services.Loader.processMessage(Loader.java:65)
	at gov.gtas.services.LoaderMain.processSingleFile(LoaderMain.java:162)
	at gov.gtas.services.LoaderMain.processListOfFiles(LoaderMain.java:90)
	at gov.gtas.services.LoaderMain.main(LoaderMain.java:70)

**Comment by svempati2006** [comment]
Can you send me the file you are using to reproduce this exception?


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Dev branch.Pl review.
