### ISSUE TITLE
DEV | cannot load APIS

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#787]
java.lang.ArrayIndexOutOfBoundsException: 5
	at gov.gtas.services.LoaderUtils.isPrimeFlight(LoaderUtils.java:331)
	at gov.gtas.services.LoaderRepository.processFlightsAndPassengers(LoaderRepository.java:215)
	at gov.gtas.services.LoaderRepository$$FastClassBySpringCGLIB$$7a0efd7e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at gov.gtas.services.LoaderRepository$$EnhancerBySpringCGLIB$$47b9021d.processFlightsAndPassengers(<generated>)
	at gov.gtas.services.ApisMessageService.load(ApisMessageService.java:110)
	at gov.gtas.services.Loader.processMessage(Loader.java:103)
	at gov.gtas.job.scheduler.LoaderScheduler.processSingleFile(LoaderScheduler.java:200)
	at gov.gtas.job.scheduler.LoaderScheduler.receiveMessage(LoaderScheduler.java:225)
	at gov.gtas.job.scheduler.LoaderWorkerThread.processCommand(LoaderWorkerThread.java:71)
	at gov.gtas.job.scheduler.LoaderWorkerThread.run(LoaderWorkerThread.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dje04001** [comment]
Adding APIS prime flight check to redis to enable APIS loading through the job scheduler.
