### ISSUE TITLE
Test Plan | rule / hit generation

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#902]
come up with structured and hopefully automated approach to testing rule creation to ensure the drl strings have proper syntax, and that hits are created and stored in the database.

**Comment by originalname51** [comment]
We should consider pulling in [this pull request working with user defined rules](https://github.com/US-CBP/GTAS/pull/882/)

**Comment by originalname51** [comment]
Made PR to fix unit test.

Looking to see how hard it would be to parse entire messages into database so we can test rule hits on PNR/APIS data.

**Comment by dje04001** [comment]
- [ ] Load sample data messages
- [ ] Create rule(s) that match passenger details contained in the sample messages
- [ ] Determine expected count of "Hits" 
- [ ] Set messages to "Loaded" status in the database
- [ ] Determine messages ran through rules engine (message status will be set to "Analyzed"
- [ ] compare expected count of "Hits" to records in "hit_detail" or "hits_disposition" in the database
- [ ] compare expected count to or to the cases created on the front end

**Comment by gtasautumn** [comment]
Testing steps

Rules are used to query new data and report matches. Rules must be saved before the data is loaded, but it may help to view the data first to decide what rules to build, then save the rules and re-load the data.

Viewing the data before creating Rules
1. Once you have received the data files, drop them into your c:\MESSAGES folder for processing.
2. Log in and view the loaded data on the Flights page (you will be redirected there after login). You will have multiple rows if your dataset included multiple flights.
3. Click on the link in the Passengers column to view the passenger list, displayed in another table.
4. Here you can sort by column, etc, to determine how many records a filter on those columns should return. Additional fields, like SEAT, AGENCY, EMAIL can be viewed on the details page for each passenger record.

You can then create rules by navigating to Tools>Rules. Then you will need to reload your data.
1. Change the status of the messages in the DB from ANALYZED to LOADED in the MESSAGE_STATUS table. The system will re-process the records and run your saved rules.
2. Go back to the Passenger list and verify that for each passenger record that matches a rule there is
 a flag in the Rule Hits column, and a new case under Cases.

**Comment by lnpeng** [comment]
Thanks for the helpful steps description. 

When I tried to test the rules and hit generation at localhost:8080/gtas and create/save a rule, I see the following exceptions are thrown out from tomcat console:

09:27:33.513 [http-nio-8080-exec-8] ERROR gov.gtas.error.BasicErrorHandler -
gov.gtas.error.CommonServiceException: The system generated an unknown error cod
e 'SYSTEM_ERROR'.
        at gov.gtas.error.BasicErrorHandler.createExceptionAndLog(BasicErrorHand
ler.java:209)
        at gov.gtas.error.BasicErrorHandler.createException(BasicErrorHandler.ja
va:102)
        at gov.gtas.error.BasicErrorHandler.createException(BasicErrorHandler.ja
va:99)
        at gov.gtas.error.BasicErrorHandler.createException(BasicErrorHandler.ja
va:99)
        at gov.gtas.error.BasicErrorHandler.createException(BasicErrorHandler.ja
va:112)
        at gov.gtas.svc.RuleManagementServiceImpl.createKnowledgeBaseFromDRLStri
ng(RuleManagementServiceImpl.java:76)
        at gov.gtas.svc.RuleManagementServiceImpl.createKnowledgeBaseFromUdrRule
s(RuleManagementServiceImpl.java:117)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflecti
on(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJo
inpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.
invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.in
voke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynami
cAopProxy.java:212)
        at com.sun.proxy.$Proxy367.createKnowledgeBaseFromUdrRules(Unknown Sourc
e)
        at gov.gtas.svc.UdrServiceImpl.recompileRules(UdrServiceImpl.java:304)
        at gov.gtas.svc.UdrServiceImpl.createUdr(UdrServiceImpl.java:287)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflecti
on(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJo
inpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:163)
        at org.springframework.security.access.intercept.aopalliance.MethodSecur
ityInterceptor.invoke(MethodSecurityInterceptor.java:69)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.
invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.in
voke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynami
cAopProxy.java:212)
        at com.sun.proxy.$Proxy368.createUdr(Unknown Source)
        at gov.gtas.controller.UdrManagementController.createUDR(UdrManagementCo
ntroller.java:181)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvok
e(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeF
orRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServ
let.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53
)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInter
ceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInter
ceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.do
Filter(ExceptionTranslationFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFi
lter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticati
onFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwar
eRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter
.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.ConcurrentSessionFilter.doFi
lter(ConcurrentSessionFilter.java:155)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AbstractAuthenticatio
nProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.d
oFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at com.allanditzel.springframework.security.web.csrf.CsrfTokenResponseHe
aderBindingFilter.doFilterInternal(CsrfTokenResponseHeaderBindingFilter.java:52)

        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterIn
ternal(HeaderWriterFilter.java:74)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFi
lter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManage
rIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(Fi
lterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChai
nProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(D
elegatingFilterProxy.java:357)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(Delegat
ingFilterProxy.java:270)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAcce
ssLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java
:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
ht.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
Protocol.java:836)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1747)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
e.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo
lExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo
olExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)


And I tried to test the rules and hit generation at https://192.168.2.141:8443/gtas/. When I go to the Flights view, I see many flights and messages that have been loaded. I performed the following steps:
1)  Create a rule (i.e. age greater than 35)
2)  Change the status of the messages in the DB from ANALYZED to LOADED.
3)  Go to the rules page and see that there are ~185 hits for the newly created rule.
4)  Go to the Flights page and see that there are about several hundreds of hits for all the rules (passenger age, checked bags, etc).

Based on the above, how do I know that the 185 hits for the newly created rule is correct? Should I assume it is correct and verify the number of hits in the database (i.e hit_detail and hits_disposition)?

"Go back to the Passenger list and verify that for each passenger record that matches a rule there is
a flag in the Rule Hits column, and a new case under Cases."

When I log in https://192.168.2.141:8443/gtas/, there are rules existing in the database. I see there are hits of those existing rules on Passenger list. How do I distinguish hits of the existing rules with the hits of the new rule on Passenger list? As there are about several hundreds of hits for all the rules, it is not realistic to click on each passager to see which rules are hit. Should I disable the exisiting rules to see only the hits of the new rule in the Passenger list?

Sorry for the confusion.  Thanks for your help.

**Comment by lnpeng** [comment]
I created 24 rules and 25 queries. Among them about 6 rules generated the number of the hits which is inconsistent with the number of the query result records. All of the 6 rules utilize AND/OR of two groups. I attached the 6 rules as following:

**Rule 17**: AND (OR (FLIGHT-PASSENGER Reservation Reference Number begins with AB)
                             (DWELL TIME Lay over Time greater 2))
113 hits vs 100 records

**Rule 19** : OR (AND (DWELL TIME Lay over Time greater 2))
                        (AND (BAG Bag Measurement Count greater 3)
                                    (BAG Bag Weight Measurement (kg) greater 50)
                                    (BAG Destination Country equal Unite States of America (USA))
                                    (BAG Destination Airport equal Washington Dulles Intl (IAD))
                                    (BAG Airline equal UA)) 
179 hits vs 93 records

**Rule 20** : OR (AND (FLIGHT-PASSENGER Reservation Reference Number begins with AB))
                        (AND (PNR Days Booked Before Travel less 3)
                                    (PNR Bag-Count greater 5)
                                    (FLIGHT LEG Origin equal IAD))
23 hits vs 10 records

**Rule 22**: OR (AND (FLIGHT-PASSENGER Reservation Reference Number begins with AB))
                    (AND (PHONE Number begins with 1))
67 hits vs 54 records

**Rule 23**: OR (AND (DWELL TIME Lay over Time greater 2))
                    (AND (PHONE Number begins with 1))
154 hits vs 0 records

**Rule 24**: OR (AND (BAG Bag Measurement Count greater 3)
                                    (BAG Bag Weight Measurement (kg) greater 50)
                                    (BAG Destination Country equal Unite States of America (USA))
                                    (BAG Destination Airport equal Washington Dulles Intl (IAD))
                                    (BAG Airline equal UA))
                    (AND (PHONE Number begins with 1))
132 hits vs 49 records

And the following rule can not be saved but can be saved as a query:

Query 25: AND (HITS Has Rule Hit Yes)
                         (HITS Rules Hit Id equal 1)
